CREATE DATABASE IF NOT EXISTS photo_editor_db;
USE photo_editor_db;

CREATE TABLE images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    data LONGBLOB NOT NULL,
    width INT,
    height INT,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE adjustments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_id INT NOT NULL,
    type VARCHAR(50) NOT NULL,
    value VARCHAR(255),
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE
);